import type { Metadata } from "next";
import "./globals.css";
import { AuthNav } from "@/components/Navigation/AuthNav";
import { usePathname } from "next/navigation";
import { AuthProvider } from "./(providers)/AuthContext";
import { Footer } from "@/components/Footer/Footer";

export const metadata: Metadata = {
  title: "JBPRS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen w-full font-sans flex flex-col overflow-auto">
        <AuthProvider>
          <AuthNav show={true} />
          <div className=" flex flex-col min-h-full flex-grow bg-back bg-center bg-no-repeat bg-cover">{children}</div>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
